spring:
  datasource:
    url: jdbc:h2:mem:transportedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true

#spring.datasource.url=jdbc:postgresql://localhost:5432/pokemonapicourse
#spring.datasource.username=postgres
#spring.datasource.password=test
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true